name: CI

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:

    name: Build with bun latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build with bun latest
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Rebuild
        run: bun run build

  check:

    name: Run all checks
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Build with bun latest
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint check
        run: bun lint

      - name: Format check
        run: bun prettier

      - name: Type check
        run: bun check-types